name: CI

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/checkout@v4

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }}

  android:
    runs-on: ubuntu-latest
    needs: create-release

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Fetch Flutter dependencies
        run: flutter pub get

      - name: Build
        run: flutter build apk

      - if: startsWith(github.ref, 'refs/tags/v')
        name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.ref_name }} build/app/outputs/flutter-apk/app-release.apk
